# Generated by Django 6.0.5 on 2026-05-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoveNote',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='date_taken',
        ),
    ]
