# Generated by Django 6.0.5 on 2026-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_app', '0002_lovemessage_delete_lovenote_remove_photo_date_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The pickup line question to ask', max_length=500)),
                ('expected_keywords', models.CharField(help_text="Comma-separated keywords that will trigger the sweet response (e.g., 'time,clock,what time')", max_length=500)),
                ('sweet_response', models.TextField(help_text='The romantic response to show after she answers')),
                ('hint', models.CharField(blank=True, help_text='A small hint to help her answer', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order in which questions appear')),
                ('is_active', models.BooleanField(default=True, help_text='Show this pickup line in the game')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
