# Generated by Django 6.0.5 on 2026-05-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_app', '0003_pickupline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Song title (e.g., 'Perfect - Ed Sheeran')", max_length=200)),
                ('spotify_embed_url', models.URLField(help_text='Spotify embed URL (from Share > Embed)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this song on the website')),
                ('order', models.IntegerField(default=0, help_text='Display order (1, 2, 3...)')),
                ('song_type', models.CharField(choices=[('main', 'Main Love Song'), ('bonus', 'Bonus Love Song')], default='bonus', max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
